name: Deploy to Ubuntu EC2

on:
  push:
    branches: ['master']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      env: 
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      run: |
        # Setup SSH
        mkdir -p ~/.ssh
        echo "$PRIVATE_KEY" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key

        # Archive the application code using zip
        zip -r myapp.zip .

        # Transfer the code to EC2
        scp -o StrictHostKeyChecking=no \
            -i ~/.ssh/deploy_key myapp.zip \
            $EC2_USERNAME@${{ secrets.EC2_HOST }}:/home/$EC2_USERNAME

        # Deploy to EC2
        ssh -o StrictHostKeyChecking=no \
            -i ~/.ssh/deploy_key \
            $EC2_USERNAME@${{ secrets.EC2_HOST }} << 'EOF'

            # Navigate to home directory
            cd /home/$USER
            mkdir -p myapp

            # Unzip the application code into the myapp directory
            unzip -o myapp.zip -d myapp 
            cd myapp

            # Install dependencies
            npm ci

            # Set environment variable for production
            export NODE_ENV=production

           # Build the app for production
            npm run build

            npm install -g serve

            # Start the application using PM2 and 'serve' to serve static files
            pm2 restart serve --name "myapp" -- -s dist || pm2 start serve --name "myapp" -- -s dist

            # Save the PM2 process list
            pm2 save --force

        EOF
