name: Deploy to Ubuntu EC2

on:
  push:
    branches: ['master']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      env: 
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      run: |
        # setup ssh
        mkdir -p ~/.ssh
        echo "$PRIVATE_KEY" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key

        # Archive the application code
        tar -czf myapp.tar.gz .

        # Transfer the code to EC2
        scp -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key myapp.tar.gz $EC2_USERNAME@${{ secrets.EC2_HOST }}:/home/$EC2_USERNAME


        # deploy to EC2
        ssh -o StrictHostKeyChecking=no \
            -i ~/.ssh/deploy_key \
            $EC2_USERNAME@${{ secrets.EC2_HOST }} << 'EOF'

            #Update project

            cd /home/$USER
            mkdir -p myapp
            tar -xzf myapp.tar.gz -C myapp
            cd myapp

           

            #Install dependencies
            npm ci

            export NODE_ENV=production

            #Restart Application
            pm2 restart app.js || pm2 start app.js
            pm2 save

            EOF

